### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by Lukas-Stuehrk** [square/Cleanse#30]
Thanks for making this project open source. The ideas and concepts look solid and more promising than the existing DI frameworks for Swift.

From what I see in the source code, you already try to support Swift 3. However it seems that you target one of the early previews of Swift 3. The language has changed very much with the latest swift evolutions and because of that Cleanse doesn't work with the latest beta of Swift 3.

Are you planning to support Swift 3 in the near future?

Also, there seems to be some work where you have small corrections in the APIs (e.g. #27) but development seems to have stalled. Do you have some kind of roadmap or another document where you outline future development?

**Comment by mikelikespie** [comment]
@Lukas-Stuehrk We're definitely planning on swift 3. We're going to finish up this [PR](https://github.com/square/Cleanse/pull/27) for 2.3 then convert it to 3.0 for our big 1.0 release.

All we have to do for that PR is really update the docs. (it is where we're headed for the API though).

thanks for your patience!

-Mike

**Comment by mikelikespie** [comment]
@Lukas-Stuehrk check out the swift-3 branch I just created for #36 . YMMV, but I'm guessing it will work well

**Comment by hzsweers** [comment]
Mileage is varying, the branch doesn't seem to compile in its current state if I try to pull it in via carthage

**Comment by mikelikespie** [comment]
@hzsweers Can you paste issue with Carthage? I don't use carthage, but I do know that this branch works with the xcode project that is checked in. Will be glad to help!

**Comment by ddengler** [comment]
Tried this for the first time as well. Does not install with Carthage. Fails with the following errors:

```
error: module 'Cleanse' was not compiled for testing 
@testable import Cleanse
```

**Comment by ddengler** [comment]
The PR #41 seems to fix the issue.

**Comment by hzsweers** [comment]
@mikelikespie yep looks like that PR should fix it

**Comment by mikelikespie** [comment]
Applied similar fix to what was in #41

**Comment by hzsweers** [comment]
@mikelikespie looks like it's still broken in the rc cut. Was it before or after your fix?

```
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/pandanomic/dev/iOS/CatchUp/Carthage/Checkouts/Cleanse/Cleanse.xcworkspace -scheme Cleanse -configuration Release -derivedDataPath /Users/pandanomic/Library/Caches/org.carthage.CarthageKit/DerivedData/Cleanse/1.0.0-a.3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/8l/wh_pvt9504930hb0srt6kdqh0000gn/T/carthage-xcodebuild.4qxePJ.log
```

**Comment by AAverin** [comment]
Still doesn't seem to work with Cartage on newly created project with Xcode 8.3.2

**Comment by holmes** [comment]
merged to master, pod'd as 1.0-rc1
